---
# handlers file for memoryleak.newrelic-php
- name: apache-restarted-handler
  service:
    name: "{{ apache_service_name }}"
    state: restarted

- name: nginx-restarted-handler
  service:
    name: "{{ nginx_service_name }}"
    state: restarted

- name: php-restarted-handler
  service:
    name: "{{ php_service_name }}"
    state: restarted

- name: newrelic-daemon-restart-handler
  service:
    name: newrelic-daemon
    state: restarted

- name: newrelic-daemon-stop-handler
  service:
    name: newrelic-daemon
    state: stopped

- name: newrelic-daemon-start-handler
  service:
    name: newrelic-daemon
    state: started